name: Telemetria Nexpro

on:
  schedule:
    - cron: '0 10 1 * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install selenium gspread google-auth

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Ejecutar script
        env:
          NEXPRO_USUARIO: ${{ secrets.NEXPRO_USUARIO }}
          NEXPRO_PASSWORD: ${{ secrets.NEXPRO_PASSWORD }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python nexpro_telemetria.py
