name: Carga datos Nexpro

on:
  schedule:
    # Día 1 de cada mes - 06:00 AM Argentina (09:00 UTC)
    - cron: '0 9 1 * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Inicio
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install selenium gspread google-auth

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Ejecutar script
        env:
          NEXPRO_USUARIO: ${{ secrets.NEXPRO_USUARIO }}
          NEXPRO_PASSWORD: ${{ secrets.NEXPRO_PASSWORD }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python carga_aut_datos_nexpro.py > salida.txt 2>&1

      - name: Fin
        if: always()
        run: echo "END_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Mail éxito
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_FROM }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Carga datos Nexpro OK"
          to: ${{ secrets.EMAIL_FROM }}
          from: GitHub Nexpro
          body: |
            Estado: EXITOSO

            Proceso:
            carga_aut_datos_nexpro.py

            Hora Argentina:
            $(TZ=America/Argentina/Buenos_Aires date)

            Duración:
            $((END_TIME - START_TIME)) segundos

            Workflow:
            ${{ github.workflow }}

            Run:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Mail error
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_FROM }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Error carga datos Nexpro"
          to: ${{ secrets.EMAIL_FROM }}
          from: GitHub Nexpro
          body: |
            Estado: FALLÓ

            Proceso:
            carga_aut_datos_nexpro.py

            Hora Argentina:
            $(TZ=America/Argentina/Buenos_Aires date)

            Duración:
            $((END_TIME - START_TIME)) segundos

            Revisar logs:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
